//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Vinusha.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {
            this.Teacher_Subject_Allocation = new HashSet<Teacher_Subject_Allocation>();
        }
    
        public long SubjectID { get; set; }
        [Required(ErrorMessage = "Subject Code is required")]
        [DisplayName("Subject Code")]
        public string SubjectCode { get; set; }
        [Required(ErrorMessage = "Subject Nmae is required")]
        [DisplayName("Subject Name")]
        public string Name { get; set; }
        
        [DisplayName("Active Status")]
        public bool IsEnable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teacher_Subject_Allocation> Teacher_Subject_Allocation { get; set; }
    }
}
